onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - elm
  - elm-format
  - elm-json
  - esbuild

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@<6.0.6: '>=6.0.6'
  form-data@<2.5.4: '>=2.5.4'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
